### ISSUE TITLE
When opening a patch file, a filter for *.kvi files should be set

### ISSUE THREAD

**Issue by ensonic** [Kymorphia/alkimiya#1]
setting a filter on the file chooser will help to quickly find the file.

**Comment by Kymorphia** [comment]
Kymorphia Vector Instrument file filters have been added for the extensions .kvi and .kvz (compressed) to the file open dialog and will be in the 0.9.1 release. Note however, that .kvz compressed file support isn't yet implemented.  Thanks for reporting this.
